services:
  lavalink:
    image: fredboat/lavalink
    container_name: lavalink
    restart: unless-stopped
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
    hostname: lavalink
    ports:
      - '2333:2333'
    networks:
      zhe-nu-net:
        ipv4_address: 172.16.1.4

  discord-bot:
    image: neoryssy/zhe_nu
    depends_on:
      - lavalink
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs:rw
    networks:
      zhe-nu-net:
        ipv4_address: 172.16.1.5

networks:
  zhe-nu-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
